name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: install and build
        run: cd frontend && npm install && npm build && npm start

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "needs-workshop"
          slot-name: "dev"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_xxxx }}
          package: .
